Drop pyhdf
NASA-IMPACT/hls-thumbnails pull request #5
Opened 2024-04-30 00:11 UTC by chuckwondo

2024-04-30 15:27 UTC, sharkinsspatial requested changes

2024-04-30 15:27 UTC, sharkinsspatial commented on Dockerfile
@chuckwondo We should no longer need a full `osgeo/gdal:ubuntu` image for testing as we no longer need the HDF dependencies.  You should be able to use an alpine image with the plain rasterio 1.1.3 wheel installed.

2024-04-30 15:27 UTC, sharkinsspatial commented on tests/test_thumbnails.py
Can we download the thumbnail produced for the test granule by the original code and perform a checksum analysis to verify that our new output is the same?  I'm not sure if they will be identical given our methodology change but ideally we want the thumbnail to be almost identical.

2024-04-30 15:30 UTC, chuckwondo commented on tests/test_thumbnails.py
Sure! I did manually test that the checksums are indeed identical. I will implement your suggestion to integrate checksum comparison directly in the unit tests.

2024-04-30 15:30 UTC, chuckwondo commented on Dockerfile
Ah, cool. I'll update.

2024-04-30 21:09 UTC, chuckwondo commented on tests/test_thumbnails.py
Done

2024-04-30 21:12 UTC, chuckwondo commented on Dockerfile
Do you have a specific image in mind?

I tried `remotepixel/alpine-rasterio:gdal3.0`, and I got that to work, but it has python 3.8 installed, not python 3.6, so I had to tweak `tox.ini` to use `envlist = py3` instead of `envlist = 3.6`. Is that what you're looking for?

2024-04-30 21:40 UTC, chuckwondo commented on Dockerfile
I noticed that this image has rasterio 1.1.2 installed, so I explicitly pip installed 1.1.3, but that causes an exception:

```plain
 E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

2024-05-01 15:05 UTC, chuckwondo commented on Dockerfile
@sharkinsspatial, I was spending too much time trying to wrestle with alpine images, so I simply changed from ubuntu-full to ubuntu-small and trimmed some system packages, which shaved about 1 GB from the image size. Is that sufficient?

2024-05-02 17:07 UTC, sharkinsspatial approved these changes

2024-05-02 17:33 UTC, merged